cookie:
  expiry_days: 30
  key: some_random_key_here
  name: ai_coach_cookie
credentials:
  usernames:
    ahmed:
      email: www.arshadansari376@gmail.com
      name: ahmed raza
      password: $2b$12$ZKJu/3sbuhJIn6n3KCkaLOl.6ZuAE5qlOh38yiF1Nc0lcnMI5AVJi
    aman123:
      email: ama1234@gmail.com
      name: amam
      password: $2b$12$R1uO9TvqvycKzpBa0byzd.XRy1.jrR79mAk3LEot3JcQJbURy2egq
    ansari889:
      email: wasiqirshad947@gmail.com
      name: Ansari Wasiq
      password: $2b$12$.6mGXApGEn2S8zr7ptDVS.ho7NJ.bdyxxOg5WeJS8bKahwHtG3ZGe
    ansari88999:
      email: wasiqirshad947@gmail.com
      name: Ansari Wasiq
      password: $2b$12$HozfFTFAgpSxSL0bE4lBfeWc.zk1nVVQPvCnBiGPjos7gf9UGcv76
    wasiqirshad2666:
      email: wasiqirshad264@gmail.com
      name: Muhammad Wasiq Ansari
      password: $2b$12$N6EBL2PQY8TrH0oOf.fr1.t5EYNmerbclahQetVmIK/ndP5X/Cxmm
